version: '2'
services:
  preview:
    build: .
    command: rake preview
    ports:
      - "4000:4000"
    volumes:
      - ./:/app

  bash:
    stdin_open: true
    tty: true
    build: .
    command: /bin/bash
    volumes:
      - ./:/app:delegated
      - ~/.gitconfig:/root/.gitconfig:ro

    # SSH Forwarding (run ./setup.sh to add your key)
    # Note: we can't use $SSH_AUTH_SOCK directly
    # due to some limitations on mac.
    # For solution, see:
    #   https://github.com/nardeas/docker-ssh-agent
    # For limitation description and tracking, follow:
    #   https://github.com/docker/for-mac/issues/483
    volumes_from:
      - ssh-agent
    environment:
      SSH_AUTH_SOCK: /.ssh-agent/socket
    depends_on:
      - ssh-agent

  ssh-agent:
    image: nardeas/ssh-agent
